### ISSUE TITLE
Accessing response headers is not working

### ISSUE THREAD

**Issue by mac-cain13** [ngonzalvez/rest-facade#40]
The [readme indicates](https://github.com/ngonzalvez/rest-facade#response-headers) that it is possible to access response headers by a second argument from the promise or as a third argument from the callback. As implemented in PR #27.

This is not working at the moment, because the second argument of a promise is not passed through. Promises normally only have one value that they resolve to, not multiple. For example:

```js
Users
  .getAll()
  .then(function (body, headers) {
    console.log(headers) // This will always log `null`
  })
```

If I add a `console.log` at [Client.js:379](https://github.com/ngonzalvez/rest-facade/blob/v1.10.1/src/Client.js#L379) that logs `res.header` I see that the headers are indeed there and they are passed to the resolve method. But adding a `promise.then((_, header) => { console.log(header) })` on line 385 shows that the headers are not available for consumers of the promise and the second argument is always `null`.

I think the promise should be resolved with the whole response object or headers should be accessible in another way.

**Comment by ngonzalvez** [comment]
Hi @mac-cain13, sorry for taking so long to reply.

It seems that promises only resolve with one param, so the second one is ignored. I'll fix this in a new version, but it will be a breaking change, since I will have to pass the entire `response` object to the resolved promise. You'd use it this way:

```javascript
Users
  .getAll()
  .then(function ({ body, headers }) {  // Note the curly braces.
    console.log(headers);
  });
```

I'll release this as v2 soon along with a few other changes. In the meantime the workaround is to use a callback function instead of the promise version, the callback function works as it should.

**Comment by mac-cain13** [comment]
Thanks, that seems like a good solution! 👍 
Looking forward to the new version.

**Comment by jamiesoncj** [comment]
Hey @ngonzalvez just wanted to ask a question about this issue. You mentioned above that

> the callback function works as it should.

I'm not sure this is the case. In my testing, even using callback function results in an undefined second variable (where `headers` would be expected).

I would imagine this is due to the use of Promise.resolve within the `sendRequest()` function in `Client.js`: https://github.com/ngonzalvez/rest-facade/blob/master/src/Client.js#L404

I had a quick look for a test case to check, because in my usage, response headers are inaccessible using either callbacks or Promises style. Have I overlooked the proper usage (am just I being stupid)?

Thank you.
