### ISSUE TITLE
Module error 'superagent'.

### ISSUE THREAD

**Issue by NalinSajwan** [ngonzalvez/rest-facade#60]
Version of `1.16.0` of the SDK is not usable at this point, because for some reason `superagent` is no longer listed as dependencies, but as peerDependencies.

Immediately upon require('') an error is thrown.
```
Error: Cannot find module 'superagent'

Require stack:

- /work/services/analytics/node_modules/rest-facade/src/Client.js

- /work/services/analytics/node_modules/rest-facade/src/index.js
```
![image](https://user-images.githubusercontent.com/10107926/135609722-6ddb6842-2224-4fa3-ba1f-4554735e0989.png)

**Comment by ngonzalvez** [comment]
Hi, you are right. I messed it up when fixing merge conflicts. Thanks for letting me know. I'll merge your PR.

**Comment by ngonzalvez** [comment]
Fixed by PR #61 in `v1.16.1` . I'm closing this.

**Comment by gragland** [comment]
With `rest-facade@1.16.1` I'm getting the error `Cannot find module 'superagent-proxy'` when using the `node-auth0` library: https://github.com/auth0/node-auth0/issues/663

**Comment by ngonzalvez** [comment]
In order to use a proxy you should install `superagent-proxy` it as a dependency in your project. Please refer to the [docs](https://github.com/ngonzalvez/rest-facade#proxy-support).

**Comment by ngonzalvez** [comment]
I sent a PR to fix this in node-auth0.

**Comment by jamiesoncj** [comment]
Sorry to comment on a closed issue @ngonzalvez - thank you for the recent updates to this package.

I am also seeing the error `Cannot find module 'superagent-proxy'`. However, I am not using a proxy in my project. I think that it's possible that the `require()` call may have been unintentionally left in the file header of `Client.js`:

https://github.com/ngonzalvez/rest-facade/blob/e9add26810c9df54ab00a03769c1a0e0230b4db2/src/Client.js#L14-L15

Since it is also duplicated at lines 40-41, which seems appropriate.

I have opened a PR for this here: https://github.com/ngonzalvez/rest-facade/pull/62
