### ISSUE TITLE
Superagent deprecation warning

### ISSUE THREAD

**Issue by zackdotcomputer** [ngonzalvez/rest-facade#66]
Current version of superagent (^5.1.1) is generating a deprecation warning:
```
npm WARN deprecated superagent@5.3.1: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
```

**Comment by mradulbohra** [comment]
Yes, facing the same issue as well

**Comment by koyedele** [comment]
https://github.com/ngonzalvez/rest-facade/pull/65 should fix this

**Comment by philip-nicholls** [comment]
I don't think that is merged and published yet.  Latest rest-facade on npm is 1.16.3

rest-facade@1.16.3
    └─┬ superagent@5.3.1

FYI, now there is superagent v8 so maybe worth looking in to, I'm not sure.

**Comment by ngonzalvez** [comment]
@philip-nicholls it could be interesting, but since it is 3 major versions ahead, the change to `supergent` v8 would be a major version change for `rest-facade`. I'm planning on doing some changes and releasing a `rest-facade` v2, so I'll take it into account.

BTW, the warning should go away with v1.16.4. Closing this issue.
